INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2505A', 'DVC', '离心液箱', '滤液');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2506', 'DVC', '离心液泵', '滤液');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2507', 'DVC', '离心液泵', '滤液');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2508', 'DVC', '离心液泵', '滤液');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2509', 'DVC', '滤液泵', '滤液');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2601', 'DVC', '高效浓缩机', '浓缩');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2602', 'DVC', '高效浓缩机', '浓缩');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2608', 'DVC', '浓缩机底流泵', '底流');
INSERT INTO `tb_thing` (`parent_thing_id`, `thing_code`, `thing_category_code`, `thing_name`, `thing_shortname`) VALUES (NULL, '2609', 'DVC', '浓缩机底流泵', '底流');