UPDATE `tb_thing` SET thing_shortname='压滤' WHERE thing_code='2492';
UPDATE `tb_thing` SET thing_shortname='压滤' WHERE thing_code='2493';
UPDATE `tb_thing` SET thing_shortname='压滤' WHERE thing_code='2494';
UPDATE `tb_thing` SET thing_shortname='压滤' WHERE thing_code='2495';
UPDATE `tb_thing` SET thing_shortname='压滤' WHERE thing_code='2496';
UPDATE `tb_thing` SET thing_shortname='压滤' WHERE thing_code='2496A';
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2502', 'DVC', '压滤煤泥转载刮板', null, null, null, '煤泥');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2553', 'DVC', '煤泥转载带式输送机', null, null, null, '煤泥');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2529', 'DVC', '压滤系统扫地泵', null, null, null, '扫地');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2485', 'DVC', '压滤机入料桶', null, null, null, '入料');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2497', 'DVC', '压滤煤泥收集刮板', null, null, null, '煤泥');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2487', 'DVC', '压滤机入料泵', null, null, null, '入料');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2498', 'DVC', '压滤煤泥收集刮板', null, null, null, '煤泥');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2488', 'DVC', '压滤机入料泵', null, null, null, '入料');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2486', 'DVC', '压滤机入料桶', null, null, null, '入料');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2499', 'DVC', '压滤煤泥收集刮板', null, null, null, '煤泥');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2489', 'DVC', '压滤机入料泵', null, null, null, '入料');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2500', 'DVC', '压滤煤泥收集刮板', null, null, null, '煤泥');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2490', 'DVC', '压滤机入料泵', null, null, null, '入料');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2501', 'DVC', '压滤煤泥收集刮板', null, null, null, '煤泥');
INSERT INTO `tb_thing`(parent_thing_id,thing_code,thing_category_code,thing_name,thing_type1_code,thing_type2_code,thing_type3_code,thing_shortname) VALUES(null, '2491', 'DVC', '压滤机入料泵', null, null, null, '入料');
