
-- ----------------------------
-- Records of tb_metric
-- ----------------------------
INSERT INTO `tb_metric` VALUES ('1', 'SIG', '电流0', 'CURRENT0', 'PR', 'CURRENT', null, 'FLT', null);
INSERT INTO `tb_metric` VALUES ('2', 'SIG', '电流1', 'CURRENT1', 'PR', 'CURRENT', null, 'FLT', null);
INSERT INTO `tb_metric` VALUES ('3', 'SIG', '集控按钮0', 'LOCAL0', 'SS', 'LOCAL', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('4', 'SIG', '电流2', 'CURRENT2', 'PR', 'CURRENT', null, 'FLT', null);
INSERT INTO `tb_metric` VALUES ('5', 'SIG', '状态', 'STATE', 'S', 'STATE', null, 'INT', null);
INSERT INTO `tb_metric` VALUES ('6', 'SIG', '压滤机阶段', 'STAGE', 'S', 'STAGE', null, 'INT', null);
INSERT INTO `tb_metric` VALUES ('7', 'SIG', '水洗前移', 'WATER_FWD', 'S', 'WATER_FWD', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('8', 'SIG', '水洗后移', 'WATER_BWD', 'S', 'WATER_BWD', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('9', 'SIG', '喷头上移', 'SHOWER_UP', 'S', 'SHOWER_UP', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('10', 'SIG', '喷头下移', 'SHOWER_DWN', 'S', 'SHOWER_DWN', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('11', 'SIG', '暂停', 'PAUSE', 'S', 'PAUSE', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('12', 'SIG', '故障信号', 'FAULT', 'S', 'FAULT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('13', 'SIG', '刮板启动', 'SCRAPER_UP', 'S', 'SCRAPER_UP', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('14', 'SIG', '进料泵启动点', 'RL_PUMP_UP', 'S', 'RL_PUMP_UP', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('15', 'SIG', '松开限位0', 'LOOSE_LMT0', 'S', 'LOOSE_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('16', 'SIG', '小车限位0', 'CAR_LMT0', 'S', 'CAR_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('17', 'SIG', '手动/自动', 'AUTO', 'S', 'AUTO', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('18', 'SIG', '远程就地按钮', 'LOCAL', 'SS', 'LOCAL', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('19', 'SIG', '压紧上限', 'PRESS_ULMT', 'S', 'PRESS_ULMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('20', 'SIG', '压紧下限', 'PRESS_LLMT', 'S', 'PRESS_LLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('21', 'SIG', '压紧限位', 'PRESS_LMT', 'S', 'PRESS_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('22', 'SIG', '进料泵运行信号', 'JL_PUMP_UP', 'S', 'JL_PUMP_UP', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('23', 'SIG', '输送机运行信号\r\n', 'TRS_UP', 'S', 'TRS_UP', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('24', 'SIG', '进料上限', 'JL_ULMT', 'S', 'JL_ULMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('25', 'SIG', '压榨下限', 'PRS_LLMT', 'S', 'PRS_LLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('26', 'SIG', '小车限位1', 'CAR_LMT1', 'S', 'CAR_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('27', 'SIG', '压榨上限', 'PRS_ULMT', 'S', 'PRS_ULMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('28', 'SIG', '进料阀0开限位', 'JL_OLMT0', 'S', 'JL_OLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('29', 'SIG', '进料阀0关限位', 'JL_CLMT0', 'S', 'JL_CLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('30', 'SIG', '进料阀1开限位', 'JL_OLMT1', 'S', 'JL_OLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('31', 'SIG', '进料阀1关限位', 'JL_CLMT1', 'S', 'JL_CLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('32', 'SIG', '压榨阀开限位', 'YZ_OLMT', 'S', 'YZ_OLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('33', 'SIG', '压榨阀关限位', 'YZ_CLMT', 'S', 'YZ_CLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('34', 'SIG', '放空阀开限位', 'FK_OLMT', 'S', 'FK_OLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('35', 'SIG', '放空阀关限位', 'FK_CLMT', 'S', 'FK_CLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('36', 'SIG', '吹风阀开限位', 'CF_OLMT', 'S', 'CF_OLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('37', 'SIG', '吹风阀关限位', 'CF_CLMT', 'S', 'CF_CLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('38', 'SIG', '回流阀开限位', 'HL_OLMT', 'S', 'HL_OLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('39', 'SIG', '回流阀关限位', 'HL_CLMT', 'S', 'HL_CLMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('40', 'SIG', '过滤/水洗', 'FILTER', 'S', 'FILTER', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('41', 'SIG', '水洗后移限位', 'WT_FW_LMT', 'S', 'WT_FW_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('42', 'SIG', '水洗前移限位', 'WT_BW_LMT', 'S', 'WT_BW_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('43', 'SIG', '喷头下移限位', 'SW_DWN_LMT', 'S', 'SW_DWN_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('44', 'SIG', '喷头上移限位', 'SW_UP_LMT', 'S', 'SW_UP_LMT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('45', 'SIG', '洗布检测点', 'XB_CHK', 'S', 'XB_CHK', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('46', 'SIG', '洗布转换点', 'XB_TRSF', 'S', 'XB_TRSF', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('47', 'SIG', '洗布结束点', 'XB_END', 'S', 'XB_END', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('48', 'SIG', '压榨阀打开超时', 'PRS_OTMOUT', 'F', 'PRS_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('49', 'SIG', '压榨阀关闭超时\r\n', 'PRS_CTMOUT', 'F', 'PRS_CTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('50', 'SIG', '排空阀打开超时', 'PK_OTMOUT', 'F', 'PK_OTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('51', 'SIG', '排空阀关闭超时', 'PK_CTMOUT', 'F', 'PK_CTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('52', 'SIG', '吹风阀打开超时\r\n', 'CF_OTMOUT', 'F', 'CF_OTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('53', 'SIG', '吹风阀关闭超时\r\n', 'CF_CTMOUT', 'F', 'CF_CTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('54', 'SIG', '回流阀打开超时', 'HL_OTMOUT', 'F', 'HL_OTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('55', 'SIG', '回流阀关闭超时', 'HL_CTMOUT', 'F', 'HL_CTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('56', 'SIG', '排空超时', 'PK_TMOUT', 'F', 'PK_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('57', 'SIG', '吹风超时', 'CF_TMOUT', 'F', 'CF_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('58', 'SIG', '进料阀0打开超时', 'JL_OTMOUT0', 'F', 'JL_OTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('59', 'SIG', '进料阀0关闭超时', 'JL_CTMOUT0', 'F', 'JL_CTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('60', 'SIG', '进料阀1打开超时', 'JL_OTMOUT1', 'F', 'JL_OTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('61', 'SIG', '进料阀1关闭超时', 'JL_CTMOUT1', 'F', 'JL_CTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('62', 'SIG', '翻板打开超时', 'FB_OTMOUT', 'F', 'FB_OTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('63', 'SIG', '松开超时', 'SK_TMOUT', 'F', 'SK_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('64', 'SIG', '取板超时', 'QB_TMOUT', 'F', 'QB_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('65', 'SIG', '拉板超时', 'LB_TMOUT', 'F', 'LB_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('66', 'SIG', '翻板关闭超时', 'FB_CTMOUT', 'F', 'FB_CTMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('67', 'SIG', '压紧超时或超限', 'YJ_TMOUT', 'F', 'YJ_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('68', 'SIG', '进料超时', 'JL_TMOUT', 'F', 'JL_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('69', 'SIG', '压榨超时', 'YZ_TMOUT', 'F', 'YZ_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('70', 'SIG', '存在压榨压力，禁止松开', 'SK_FRBD', 'F', 'SK_FRBD', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('71', 'SIG', '存在压榨压力或小车未到位，禁止启动', 'START_FRBD', 'F', 'START_FRBD', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('72', 'SIG', '水洗前移超时', 'WTFW_TMOUT', 'F', 'WTFW_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('73', 'SIG', '水洗后移超时', 'WTBW_TMOUT', 'F', 'WTBW_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('74', 'SIG', '喷头下移超时', 'SWDW_TMOUT', 'F', 'SWDW_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('75', 'SIG', '喷头上移超时', 'SWUP_TMOUT', 'F', 'SWUP_TMOUT', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('76', 'SIG', '一队记录', 'T1_RCD', 'S', 'T1_RCD', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('77', 'SIG', '二队记录', 'T2_RCD', 'S', 'T2_RCD', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('78', 'SIG', '三队纪录', 'T3_RCD', 'S', 'T3_RCD', null, 'BOO', '100ms');
INSERT INTO `tb_metric` VALUES ('79', 'SIG', '当前计时', 'CRT_TIMER', 'PR', 'CRT_TIMER', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('80', 'SIG', '过程计时', 'PRC_TIMER', 'PR', 'PRC_TIMER', null, 'INT', null);
INSERT INTO `tb_metric` VALUES ('81', 'SIG', '一队过滤次数', 'T1_COUNT', 'PR', 'T1_COUNT', null, 'INT', null);
INSERT INTO `tb_metric` VALUES ('82', 'SIG', '二队过滤次数', 'T2_COUNT', 'PR', 'T2_COUNT', null, 'INT', null);
INSERT INTO `tb_metric` VALUES ('83', 'SIG', '三队过滤次数', 'T3_COUNT', 'PR', 'T3_COUNT', null, 'INT', null);
INSERT INTO `tb_metric` VALUES ('84', 'SIG', '总记录', 'TOTL_COUNT', 'PR', 'TOTL_COUNT', null, 'INT', null);
INSERT INTO `tb_metric` VALUES ('85', 'SIG', '进料延时', 'JL_DELAY', 'PR', 'JL_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('86', 'SIG', '压榨延时', 'YZ_DELAY', 'PR', 'YZ_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('87', 'SIG', '压榨延时时间', 'YZ_DL_TIME', 'PR', 'YZ_DL_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('88', 'SIG', '吹风时间', 'CF_TIME', 'PR', 'CF_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('89', 'SIG', '首次取板高速时间', '1QB_S_TIME', 'PR', '1QB_S_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('90', 'SIG', '取板高速时间', 'QB_S_TIME', 'PR', 'QB_S_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('91', 'SIG', '拉板高速时间', 'LB_S_TIME', 'PR', 'LB_S_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('92', 'SIG', '拉板高速返回时间', 'LB_SR_TIME', 'PR', 'LB_SR_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('93', 'SIG', '循环等待时间', 'XHDD_TIME', 'PR', 'XHDD_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('94', 'SIG', '喷头下方停留时间', 'SW_ST_TIME', 'PR', 'SW_ST_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('95', 'SIG', '喷头上移喷水时间', 'SW_SW_TIME', 'PR', 'SW_SW_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('96', 'SIG', '松开超时时间', 'SK_TO_TIME', 'PR', 'SK_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('97', 'SIG', '取板超时时间', 'QB_TO_TIME', 'PR', 'QB_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('98', 'SIG', '拉板超时时间', 'LB_TO_TIME', 'PR', 'LB_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('99', 'SIG', '压紧超时时间', 'YJ_TO_TIME', 'PR', 'YJ_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('100', 'SIG', '进料超时时间', 'JL_TO_TIME', 'PR', 'JL_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('101', 'SIG', '压榨超时时间', 'YZ_TO_TIME', 'PR', 'YZ_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('102', 'SIG', '排空超时时间', 'PK_TO_TIME', 'PR', 'PK_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('103', 'SIG', '吹风超时时间', 'CF_TO_TIME', 'PR', 'CF_TO_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('104', 'SIG', '进料阀0动作超时时间', 'JL_TO_TM0', 'PR', 'JL_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('105', 'SIG', '进料阀1动作超时时间', 'JL_TO_TM1', 'PR', 'JL_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('106', 'SIG', '压榨阀动作超时时间', 'YZ_TO_TM', 'PR', 'YZ_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('107', 'SIG', '排空阀动作超时时间', 'PK_TO_TM', 'PR', 'PK_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('108', 'SIG', '吹风阀动作超时时间', 'CF_TO_TM', 'PR', 'CF_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('109', 'SIG', '回流阀动作超时时间', 'HL_TO_TM', 'PR', 'HL_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('110', 'SIG', '水洗架前移超时时间', 'SXF_TO_TM', 'PR', 'SXF_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('111', 'SIG', '水洗架后移超时时间', 'SXB_TO_TM', 'PR', 'SXB_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('112', 'SIG', '喷头下移超时时间', 'SWD_TO_TM', 'PR', 'SWD_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('113', 'SIG', '喷头上移超时时间', 'SWU_TO_TM', 'PR', 'SWU_TO_TM', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('114', 'SIG', '高压卸荷时间', 'GY_TIME', 'PR', 'GY_TIME', null, 'INT', '100ms');
INSERT INTO `tb_metric` VALUES ('115', 'SIG', '系统报警选择', 'SYS_ALARM', 'SS', 'SYS_ALARM', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('116', 'SIG', '控制选择', 'CONTROL', 'SS', 'CONTROL', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('117', 'SIG', '阀门报警选择', 'GATE_ALARM', 'SS', 'GATE_ALARM', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('118', 'SIG', '刮板闭锁', 'SCR_BLK', 'SS', 'SCR_BLK', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('119', 'SIG', '总记录清零', 'TOTL_CLR', 'SS', 'TOTL_CLR', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('120', 'SIG', '一队清零', 'T1_CLR', 'SS', 'T1_CLR', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('121', 'SIG', '二队清零', 'T2_CLR', 'SS', 'T2_CLR', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('122', 'SIG', '三队清零', 'T3_CLR', 'SS', 'T3_CLR', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('123', 'SIG', '远程手动松开', 'LOOSE', 'SS', 'LOOSE', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('124', 'SIG', '远程手动取板', 'TAKE', 'SS', 'TAKE', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('125', 'SIG', '远程手动拉板', 'PULL', 'SS', 'PULL', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('126', 'SIG', '远程手动压紧', 'PRESS', 'SS', 'PRESS', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('127', 'SIG', '远程手动进料', 'FEED', 'SS', 'FEED', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('128', 'SIG', '远程手动压榨', 'SQUEESE', 'SS', 'SQUEESE', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('129', 'SIG', '远程手动吹风', 'BLOW', 'SS', 'BLOW', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('130', 'SIG', '远程报警复位', 'RESET', 'SS', 'RESET', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('131', 'SIG', '远程启动', 'RUN', 'SS', 'RUN', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('132', 'SIG', '远程暂停', 'S_PAUSE', 'SS', 'S_PAUSE', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('133', 'SIG', '远程停止', 'STOP', 'SS', 'STOP', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('136', 'SIG', '进料结束', 'FEED_OVER', 'SS', 'FEED_OVER', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('137', 'SIG', '一队选择', 'T1_CHOOSE', 'SS', 'T1_CHOOSE', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('138', 'SIG', '二队选择', 'T2_CHOOSE', 'SS', 'T2_CHOOSE', null, 'BOO', null);
INSERT INTO `tb_metric` VALUES ('139', 'SIG', '三队选择', 'T3_CHOOSE', 'SS', 'T3_CHOOSE', null, 'BOO', null);

-- ----------------------------
-- Records of tb_metrictype
-- ----------------------------
INSERT INTO `tb_metrictype` VALUES ('2', '参数类', 'PR');
INSERT INTO `tb_metrictype` VALUES ('3', '参数设定类', 'PS');
INSERT INTO `tb_metrictype` VALUES ('4', '固有属性', 'ST');
INSERT INTO `tb_metrictype` VALUES ('5', '特殊功能类', 'SF');
INSERT INTO `tb_metrictype` VALUES ('6', '状态类', 'S');
INSERT INTO `tb_metrictype` VALUES ('7', '状态设定类', 'SS');
INSERT INTO `tb_metrictype` VALUES ('8', '故障类', 'F');
INSERT INTO `tb_metrictype` VALUES ('9', '故障旁路类', 'FI');
INSERT INTO `tb_metrictype` VALUES ('10', '电流', 'CURRENT');
INSERT INTO `tb_metrictype` VALUES ('11', '频率', 'FREQUENCY');
INSERT INTO `tb_metrictype` VALUES ('12', '压力', 'PRESSURE');
INSERT INTO `tb_metrictype` VALUES ('13', '就地集控按钮', 'LOCAL');
INSERT INTO `tb_metrictype` VALUES ('18', '状态', 'STATE');
INSERT INTO `tb_metrictype` VALUES ('19', '压滤机阶段', 'STAGE');
INSERT INTO `tb_metrictype` VALUES ('20', '水洗前移', 'WATER_FWD');
INSERT INTO `tb_metrictype` VALUES ('21', '水洗后移', 'WATER_BWD');
INSERT INTO `tb_metrictype` VALUES ('22', '喷头上移', 'SHOWER_UP');
INSERT INTO `tb_metrictype` VALUES ('23', '喷头下移', 'SHOWER_DWN');
INSERT INTO `tb_metrictype` VALUES ('24', '暂停', 'PAUSE');
INSERT INTO `tb_metrictype` VALUES ('25', '故障信号', 'FAULT');
INSERT INTO `tb_metrictype` VALUES ('26', '刮板启动', 'SCRAPER_UP');
INSERT INTO `tb_metrictype` VALUES ('27', '进料泵启动点', 'RL_PUMP_UP');
INSERT INTO `tb_metrictype` VALUES ('28', '松开限位', 'LOOSE_LMT');
INSERT INTO `tb_metrictype` VALUES ('29', '小车限位', 'CAR_LMT');
INSERT INTO `tb_metrictype` VALUES ('30', '手动/自动', 'AUTO');
INSERT INTO `tb_metrictype` VALUES ('32', '压紧上限', 'PRESS_ULMT');
INSERT INTO `tb_metrictype` VALUES ('33', '压紧下限', 'PRESS_LLMT');
INSERT INTO `tb_metrictype` VALUES ('34', '压紧限位', 'PRESS_LMT');
INSERT INTO `tb_metrictype` VALUES ('35', '进料泵运行信号', 'JL_PUMP_UP');
INSERT INTO `tb_metrictype` VALUES ('36', '输送机运行信号\r\n', 'TRS_UP');
INSERT INTO `tb_metrictype` VALUES ('37', '进料上限', 'JL_ULMT');
INSERT INTO `tb_metrictype` VALUES ('38', '压榨下限', 'PRS_LLMT');
INSERT INTO `tb_metrictype` VALUES ('40', '压榨上限', 'PRS_ULMT');
INSERT INTO `tb_metrictype` VALUES ('41', '进料阀开限位', 'JL_OLMT');
INSERT INTO `tb_metrictype` VALUES ('42', '进料阀关限位', 'JL_CLMT');
INSERT INTO `tb_metrictype` VALUES ('45', '压榨阀开限位', 'YZ_OLMT');
INSERT INTO `tb_metrictype` VALUES ('46', '压榨阀关限位', 'YZ_CLMT');
INSERT INTO `tb_metrictype` VALUES ('47', '放空阀开限位', 'FK_OLMT');
INSERT INTO `tb_metrictype` VALUES ('48', '放空阀关限位', 'FK_CLMT');
INSERT INTO `tb_metrictype` VALUES ('49', '吹风阀开限位', 'CF_OLMT');
INSERT INTO `tb_metrictype` VALUES ('50', '吹风阀关限位', 'CF_CLMT');
INSERT INTO `tb_metrictype` VALUES ('51', '回流阀开限位', 'HL_OLMT');
INSERT INTO `tb_metrictype` VALUES ('52', '回流阀关限位', 'HL_CLMT');
INSERT INTO `tb_metrictype` VALUES ('53', '过滤/水洗', 'FILTER');
INSERT INTO `tb_metrictype` VALUES ('54', '水洗后移限位', 'WT_FW_LMT');
INSERT INTO `tb_metrictype` VALUES ('55', '水洗前移限位', 'WT_BW_LMT');
INSERT INTO `tb_metrictype` VALUES ('56', '喷头下移限位', 'SW_DWN_LMT');
INSERT INTO `tb_metrictype` VALUES ('57', '喷头上移限位', 'SW_UP_LMT');
INSERT INTO `tb_metrictype` VALUES ('58', '洗布检测点', 'XB_CHK');
INSERT INTO `tb_metrictype` VALUES ('59', '洗布转换点', 'XB_TRSF');
INSERT INTO `tb_metrictype` VALUES ('60', '洗布结束点', 'XB_END');
INSERT INTO `tb_metrictype` VALUES ('61', '压榨阀打开超时', 'PRS_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('62', '压榨阀关闭超时\r\n', 'PRS_CTMOUT');
INSERT INTO `tb_metrictype` VALUES ('63', '排空阀打开超时', 'PK_OTMOUT');
INSERT INTO `tb_metrictype` VALUES ('64', '排空阀关闭超时', 'PK_CTMOUT');
INSERT INTO `tb_metrictype` VALUES ('65', '吹风阀打开超时\r\n', 'CF_OTMOUT');
INSERT INTO `tb_metrictype` VALUES ('66', '吹风阀关闭超时\r\n', 'CF_CTMOUT');
INSERT INTO `tb_metrictype` VALUES ('67', '回流阀打开超时', 'HL_OTMOUT');
INSERT INTO `tb_metrictype` VALUES ('68', '回流阀关闭超时', 'HL_CTMOUT');
INSERT INTO `tb_metrictype` VALUES ('69', '排空超时', 'PK_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('70', '吹风超时', 'CF_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('71', '进料阀打开超时', 'JL_OTMOUT');
INSERT INTO `tb_metrictype` VALUES ('72', '进料阀关闭超时', 'JL_CTMOUT');
INSERT INTO `tb_metrictype` VALUES ('75', '翻板打开超时', 'FB_OTMOUT');
INSERT INTO `tb_metrictype` VALUES ('76', '松开超时', 'SK_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('77', '取板超时', 'QB_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('78', '拉板超时', 'LB_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('79', '翻板关闭超时', 'FB_CTMOUT');
INSERT INTO `tb_metrictype` VALUES ('80', '压紧超时或超限', 'YJ_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('81', '进料超时', 'JL_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('82', '压榨超时', 'YZ_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('83', '存在压榨压力，禁止松开', 'SK_FRBD');
INSERT INTO `tb_metrictype` VALUES ('84', '存在压榨压力或小车未到位，禁止启动', 'START_FRBD');
INSERT INTO `tb_metrictype` VALUES ('85', '水洗前移超时', 'WTFW_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('86', '水洗后移超时', 'WTBW_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('87', '喷头下移超时', 'SWDW_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('88', '喷头上移超时', 'SWUP_TMOUT');
INSERT INTO `tb_metrictype` VALUES ('89', '一队记录', 'T1_RCD');
INSERT INTO `tb_metrictype` VALUES ('90', '二队记录', 'T2_RCD');
INSERT INTO `tb_metrictype` VALUES ('91', '三队纪录', 'T3_RCD');
INSERT INTO `tb_metrictype` VALUES ('92', '当前计时', 'CRT_TIMER');
INSERT INTO `tb_metrictype` VALUES ('93', '过程计时', 'PRC_TIMER');
INSERT INTO `tb_metrictype` VALUES ('94', '一队过滤次数', 'T1_COUNT');
INSERT INTO `tb_metrictype` VALUES ('95', '二队过滤次数', 'T2_COUNT');
INSERT INTO `tb_metrictype` VALUES ('96', '三队过滤次数', 'T3_COUNT');
INSERT INTO `tb_metrictype` VALUES ('97', '总记录', 'TOTL_COUNT');
INSERT INTO `tb_metrictype` VALUES ('98', '进料延时', 'JL_TIME');
INSERT INTO `tb_metrictype` VALUES ('99', '压榨延时', 'YZ_TIME');
INSERT INTO `tb_metrictype` VALUES ('100', '压榨延时时间', 'YZ_DL_TIME');
INSERT INTO `tb_metrictype` VALUES ('101', '吹风时间', 'CF_TIME');
INSERT INTO `tb_metrictype` VALUES ('102', '首次取板高速时间', '1QB_S_TIME');
INSERT INTO `tb_metrictype` VALUES ('103', '取板高速时间', 'QB_S_TIME');
INSERT INTO `tb_metrictype` VALUES ('104', '拉板高速时间', 'LB_S_TIME');
INSERT INTO `tb_metrictype` VALUES ('105', '拉板高速返回时间', 'LB_SR_TIME');
INSERT INTO `tb_metrictype` VALUES ('106', '循环等待时间', 'XHDD_TIME');
INSERT INTO `tb_metrictype` VALUES ('107', '喷头下方停留时间', 'SW_ST_TIME');
INSERT INTO `tb_metrictype` VALUES ('108', '喷头上移喷水时间', 'SW_SW_TIME');
INSERT INTO `tb_metrictype` VALUES ('109', '松开超时时间', 'SK_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('110', '取板超时时间', 'QB_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('111', '拉板超时时间', 'LB_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('112', '压紧超时时间', 'YJ_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('113', '进料超时时间', 'JL_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('114', '压榨超时时间', 'YZ_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('115', '排空超时时间', 'PK_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('116', '吹风超时时间', 'CF_TO_TIME');
INSERT INTO `tb_metrictype` VALUES ('117', '进料阀动作超时时间', 'JL_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('119', '压榨阀动作超时时间', 'YZ_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('120', '排空阀动作超时时间', 'PK_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('121', '吹风阀动作超时时间', 'CF_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('122', '回流阀动作超时时间', 'HL_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('123', '水洗架前移超时时间', 'SXF_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('124', '水洗架后移超时时间', 'SXB_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('125', '喷头下移超时时间', 'SWD_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('126', '喷头上移超时时间', 'SWU_TO_TM');
INSERT INTO `tb_metrictype` VALUES ('127', '高压卸荷时间', 'GY_TIME');
INSERT INTO `tb_metrictype` VALUES ('128', '系统报警选择', 'SYS_ALARM');
INSERT INTO `tb_metrictype` VALUES ('129', '控制选择', 'CONTROL');
INSERT INTO `tb_metrictype` VALUES ('130', '阀门报警选择', 'GATE_ALARM');
INSERT INTO `tb_metrictype` VALUES ('131', '刮板闭锁', 'SCR_BLK');
INSERT INTO `tb_metrictype` VALUES ('132', '总记录清零', 'TOTL_CLR');
INSERT INTO `tb_metrictype` VALUES ('133', '一队清零', 'T1_CLR');
INSERT INTO `tb_metrictype` VALUES ('134', '二队清零', 'T2_CLR');
INSERT INTO `tb_metrictype` VALUES ('135', '三队清零', 'T3_CLR');
INSERT INTO `tb_metrictype` VALUES ('136', '远程手动松开', 'LOOSE');
INSERT INTO `tb_metrictype` VALUES ('137', '远程手动取板', 'TAKE');
INSERT INTO `tb_metrictype` VALUES ('138', '远程手动拉板', 'PULL');
INSERT INTO `tb_metrictype` VALUES ('139', '远程手动压紧', 'PRESS');
INSERT INTO `tb_metrictype` VALUES ('140', '远程手动进料', 'FEED');
INSERT INTO `tb_metrictype` VALUES ('141', '远程手动压榨', 'SQUEESE');
INSERT INTO `tb_metrictype` VALUES ('142', '远程手动吹风', 'BLOW');
INSERT INTO `tb_metrictype` VALUES ('143', '远程报警复位', 'RESET');
INSERT INTO `tb_metrictype` VALUES ('144', '远程启动', 'RUN');
INSERT INTO `tb_metrictype` VALUES ('145', '远程暂停', 'S_PAUSE');
INSERT INTO `tb_metrictype` VALUES ('146', '远程停止', 'STOP');
INSERT INTO `tb_metrictype` VALUES ('147', '进料结束', 'FEED_OVER');
INSERT INTO `tb_metrictype` VALUES ('148', '一队选择', 'T1_CHOOSE');
INSERT INTO `tb_metrictype` VALUES ('149', '二队选择', 'T2_CHOOSE');
INSERT INTO `tb_metrictype` VALUES ('150', '三队选择', 'T3_CHOOSE');

-- ----------------------------
-- Records of tb_thing
-- ----------------------------
INSERT INTO `tb_thing` VALUES ('1', null, '701', 'DVC', '煤带输送机', 'TRD', null, null);
INSERT INTO `tb_thing` VALUES ('2', '1', '701.YB.PD-1', 'DVC', '皮带秤', 'PDC', null, null);
INSERT INTO `tb_thing` VALUES ('3', null, '1301', 'DVC', '2#皮带机', 'PSJ', null, null);
INSERT INTO `tb_thing` VALUES ('4', null, 'XG.XG.1303', 'DVC', '测试设备', 'D', null, null);
INSERT INTO `tb_thing` VALUES ('5', null, 'CW_1.CW_1.1111', 'DVC', 'asdfasdf', 'D', null, null);
INSERT INTO `tb_thing` VALUES ('6', null, '2492', 'DVC', '压滤机', 'D', null, null);
INSERT INTO `tb_thing` VALUES ('7', null, '2493', 'DVC', '压滤机', 'D', null, null);
INSERT INTO `tb_thing` VALUES ('8', null, '2494', 'DVC', '压滤机', 'D', null, null);
INSERT INTO `tb_thing` VALUES ('9', null, '2495', 'DVC', '压滤机', 'D', null, null);
INSERT INTO `tb_thing` VALUES ('10', null, '2496', 'DVC', '压滤机', 'D', null, null);
INSERT INTO `tb_thing` VALUES ('11', null, '2496A', 'DVC', '压滤机', 'D', null, null);
