DELETE FROM `tb_alert_rule` WHERE metric_code in ('LE1','LE2');

UPDATE `tb_alert_rule` SET  `thing_code`='700A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700A', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700A') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700B', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700B') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700B', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700B') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700C', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700C') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700C', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700C') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700D', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700D') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700D', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700D') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='1200A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='9.00', `upper_limit`='12.00', `enable`='1' WHERE (`thing_code`='1200A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30');
UPDATE `tb_alert_rule` SET  `thing_code`='2200A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='9.00', `upper_limit`='12.00', `enable`='1' WHERE (`thing_code`='2200A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30');
UPDATE `tb_alert_rule` SET  `thing_code`='900A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='17.00', `upper_limit`='22.00', `enable`='1' WHERE (`thing_code`='900A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;

