DELETE FROM `tb_alert_rule` WHERE metric_code in ('AAD','AAD_AVG','MT','STAD','STAD_AVG','MT_AVG','NEGATIVE1_POINT8','POSITIVE1_POINT8');

INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1389', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1390', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1391', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2391', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2390', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2389', 'AAD', '1', '30', '0.00', '10.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1389', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1390', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1391', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2391', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2390', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2389', 'AAD', '1', '30', '11.00', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1389', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1390', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1391', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2391', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2390', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2389', 'MT', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1389', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1390', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1391', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2391', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2390', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2389', 'STAD', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'AAD_AVG', '1', '30', '0.00', '10.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'AAD_AVG', '1', '30', '0.00', '10.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1552', 'AAD_AVG', '1', '30', '0.00', '20.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2552', 'AAD_AVG', '1', '30', '0.00', '20.30', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'AAD_AVG', '1', '30', '10.80', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'AAD_AVG', '1', '30', '10.80', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'STAD_AVG', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'STAD_AVG', '1', '30', '0.80', '1.50', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1551', 'MT_AVG', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2551', 'MT_AVG', '1', '30', '8.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2552', 'MT_AVG', '1', '30', '10.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1552', 'MT_AVG', '1', '30', '10.00', '15.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1552', 'AAD_AVG', '1', '30', '21.50', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2552', 'AAD_AVG', '1', '30', '21.50', '50.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1345', 'NEGATIVE1_POINT8', '1', '30', '5.00', '100.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1346', 'NEGATIVE1_POINT8', '1', '30', '5.00', '100.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1347', 'NEGATIVE1_POINT8', '1', '30', '5.00', '100.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2347', 'NEGATIVE1_POINT8', '1', '30', '5.00', '100.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2346', 'NEGATIVE1_POINT8', '1', '30', '5.00', '100.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2345', 'NEGATIVE1_POINT8', '1', '30', '5.00', '100.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2345', 'POSITIVE1_POINT8', '1', '30', '0.00', '95.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2346', 'POSITIVE1_POINT8', '1', '30', '0.00', '95.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('2347', 'POSITIVE1_POINT8', '1', '30', '0.00', '95.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1347', 'POSITIVE1_POINT8', '1', '30', '0.00', '95.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1346', 'POSITIVE1_POINT8', '1', '30', '0.00', '95.00', '1');
INSERT INTO `tb_alert_rule` (`thing_code`, `metric_code`, `rule_type`, `alert_level`, `lower_limit`, `upper_limit`, `enable`) VALUES ('1345', 'POSITIVE1_POINT8', '1', '30', '0.00', '95.00', '1');

DELETE FROM `tb_alert_rule` WHERE metric_code in ('LE1','LE2');

UPDATE `tb_alert_rule` SET  `thing_code`='700A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700A', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700A') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700B', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700B') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700B', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700B') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700C', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700C') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700C', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700C') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700D', `metric_code`='LE2', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700D') AND (`metric_code`='LE2') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='700D', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='41.00', `upper_limit`='51.00', `enable`='1' WHERE (`thing_code`='700D') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;
UPDATE `tb_alert_rule` SET  `thing_code`='1200A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='9.00', `upper_limit`='12.00', `enable`='1' WHERE (`thing_code`='1200A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30');
UPDATE `tb_alert_rule` SET  `thing_code`='2200A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='9.00', `upper_limit`='12.00', `enable`='1' WHERE (`thing_code`='2200A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30');
UPDATE `tb_alert_rule` SET  `thing_code`='900A', `metric_code`='LE1', `rule_type`='1', `alert_level`='30', `lower_limit`='17.00', `upper_limit`='22.00', `enable`='1' WHERE (`thing_code`='900A') AND (`metric_code`='LE1') AND (`rule_type`='1') AND (`alert_level`='30') ;


