INSERT INTO `tb_metric` ( `metric_category_code`, `metric_name`, `metric_code`, `metric_type1_code`, `metric_type2_code`, `metric_type3_code`, `value_type`, `value_unit`) VALUES ( 'SIG', '顶水流量', 'DSFL', 'PR', 'FLOW', NULL, 'FLT', 'm^3/h');
insert into tb_metric (`metric_name`, `metric_code`) VALUES ('TCS精矿','TCS精矿');
insert into tb_metric (`metric_name`, `metric_code`) VALUES ('TCS尾矿','TCS尾矿');
insert into tb_metric (`metric_name`, `metric_code`) VALUES ('入洗原煤','入洗原煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('浅槽溢流煤','浅槽溢流煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('末中煤','末中煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('沉降煤泥','沉降煤泥');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('压滤煤泥','压滤煤泥');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('末矸石','末矸石');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('末精煤','末精煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('551生产精煤','551生产精煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('552生产洗混煤','552生产洗混煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('块原煤','块原煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('末原煤','末原煤');
INSERT INTO tb_metric  (`metric_name`, `metric_code`) VALUES ('块矸石','块矸石');
insert into tb_thing (`thing_name`, `thing_code`) VALUES ('煤质化验','coalanalysis');
