insert into rel_historydata_whitelist value('2487','CURRENT',1);
insert into rel_historydata_whitelist value('2488','CURRENT',1);
insert into rel_historydata_whitelist value('2489','CURRENT',1);
insert into rel_historydata_whitelist value('2490','CURRENT',1);
insert into rel_historydata_whitelist value('2491','CURRENT',1);
insert into rel_historydata_whitelist value('2491A','CURRENT',1);
insert into rel_historydata_whitelist value('2502','CURRENT',1);
insert into rel_historydata_whitelist value('2485','LEVEL',1);
insert into rel_historydata_whitelist value('2486','LEVEL',1);
commit;