INSERT INTO `tb_sfmon_style` VALUES ('1', 'an_1', '控制按钮', null, 'an_1.png');
INSERT INTO `tb_sfmon_style` VALUES ('2', 'bh_1', '设备保护', null, 'bh_1.png');
INSERT INTO `tb_sfmon_style` VALUES ('3', 'bh_2', '拉绳保护', null, 'bh_2.png');
INSERT INTO `tb_sfmon_style` VALUES ('4', 'cs_1', '参数显示', null, 'cs_1.png');
INSERT INTO `tb_sfmon_style` VALUES ('5', 'kz_1', '部件控制', null, 'kz_1.png');
INSERT INTO `tb_sfmon_style` VALUES ('6', 'ls_1', '部件连锁', null, 'ls_1.png');
INSERT INTO `tb_sfmon_style` VALUES ('7', 'ls_2', '参数连锁', null, 'ls_2.png');
INSERT INTO `tb_sfmon_style` VALUES ('8', 'pid_1', '比例调节', null, 'pid_1.png');
INSERT INTO `tb_sfmon_style` VALUES ('9', 'yc_1', '远程阀门', null, 'yc_1.png');

INSERT INTO `tb_metric_tag_group` VALUES ('1', 'sfmonitor', '智能监控', '2018-03-06 14:23:05');

INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('1', '状态控制', 'state_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('2', '远控阀门', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('3', '设备保护', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('4', '拉绳保护', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('5', '电机温度', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('6', '轴承温度', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('7', '轴承定子温度', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('8', '温度', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('9', '带煤量', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('10', '运行参数', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('11', '生产参数', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('12', '沉降流量', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('13', '部件控制', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('14', '电机连锁', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('15', '提耙连锁', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('16', '操作按钮', 'auxiliary_area', '0');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('17', '压力PID调节', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('18', '流量PID调节', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('19', '密度PID调节', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('20', '液位PID调节', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('21', '液位连锁', 'auxiliary_area', '1');
INSERT INTO `tb_sfmon_signal_wrapper_rule` VALUES ('22', '密度连锁', 'auxiliary_area', '1');