DELETE FROM `tb_alert_rule` WHERE lower_limit <0;
ALTER TABLE tb_alert_param_configuration_list ADD alert_type TINYINT(4);
UPDATE tb_alert_param_configuration_list SET alert_type = 1;

INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1301', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1301', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1301', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1302', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1302', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1302', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1309', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1309', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1309', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1310', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1310', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1310', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1345', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1345', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1345', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1345', 'NEGATIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1345', 'POSITIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1346', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1346', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1346', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1346', 'NEGATIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1346', 'POSITIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1347', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1347', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1347', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1347', 'NEGATIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1347', 'POSITIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1389', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1389', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1389', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1390', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1390', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1390', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1391', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1391', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1391', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1396', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1396', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1396', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1397', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1397', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1397', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1398', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1398', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1398', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1448', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1448', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1448', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1449', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1449', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1449', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1450', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1450', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1450', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1451', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1451', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1451', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1470', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1470', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1470', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1551', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1551', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1551', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1552', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1552', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1552', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1553', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1553', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1553', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1873', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1873', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1873', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1874', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1874', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('1874', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2301', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2301', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2301', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2302', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2302', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2302', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2309', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2309', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2309', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2310', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2310', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2310', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2345', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2345', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ('2345', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2345', 'NEGATIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2345', 'POSITIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2346', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2346', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2346', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2346', 'NEGATIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2346', 'POSITIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2347', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2347', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2347', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2347', 'NEGATIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2347', 'POSITIVE1_POINT8', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2389', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2389', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2389', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2390', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2390', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2390', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2391', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2391', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2391', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2396', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2396', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2396', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2397', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2397', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2397', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2398', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2398', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2398', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2448', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2448', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2448', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2449', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2449', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2449', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2450', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2450', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2450', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2451', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2451', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2451', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2470', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2470', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2470', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2551', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2551', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2551', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2552', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2552', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2552', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2553', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2553', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2553', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2873', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2873', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2873', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2874', 'AAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2874', 'MT', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2874', 'STAD', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '1551', 'AAD_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '1551', 'MT_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '1551', 'STAD_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '1552', 'AAD_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '1552', 'MT_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '1552', 'STAD_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2551', 'AAD_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2551', 'MT_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2551', 'STAD_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2552', 'AAD_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2552', 'MT_AVG', '4');
INSERT INTO `tb_alert_param_configuration_list` (`thing_code`, `metric_code`, `alert_type`) VALUES ( '2552', 'STAD_AVG', '4');


UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='+1.45平均', `metric_code`='POSITIVE1_POINT45_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg/L' WHERE (`metric_code`='POSITIVE1_POINT45_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='-1.45平均', `metric_code`='NEGATIVE1_POINT45_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg/L' WHERE (`metric_code`='NEGATIVE1_POINT45_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='+1.8平均', `metric_code`='POSITIVE1_POINT8_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg/L' WHERE (`metric_code`='POSITIVE1_POINT8_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='-1.8平均', `metric_code`='NEGATIVE1_POINT8_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg/L' WHERE (`metric_code`='NEGATIVE1_POINT8_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='1.45-1.8平均', `metric_code`='ONE_POINT45_TO1_POINT8_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg/L' WHERE (`metric_code`='ONE_POINT45_TO1_POINT8_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='+50mm平均', `metric_code`='POSITIVE50MM_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='mm' WHERE (`metric_code`='POSITIVE50MM_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='-50mm平均', `metric_code`='NEGATIVE50MM_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='mm' WHERE (`metric_code`='NEGATIVE50MM_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='PRODUCTION_INSPECT', `metric_name`='生产检查密度平均', `metric_code`='PRODUCT_INSPECT_DENSITY_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg/L' WHERE (`metric_code`='PRODUCT_INSPECT_DENSITY_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='ASSAY', `metric_name`='灰分平均', `metric_code`='AAD_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='%' WHERE (`metric_code`='AAD_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='ASSAY', `metric_name`='水分平均', `metric_code`='MT_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='%' WHERE (`metric_code`='MT_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='ASSAY', `metric_name`='硫份平均', `metric_code`='STAD_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='%' WHERE (`metric_code`='STAD_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='ASSAY', `metric_name`='发热量平均', `metric_code`='QNETAR_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg' WHERE (`metric_code`='QNETAR_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='ASSAY', `metric_name`='煤质化验密度平均', `metric_code`='ASSAY_DENSITY_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='kg/L' WHERE (`metric_code`='ASSAY_DENSITY_AVG');
UPDATE `tb_metric` SET  `metric_category_code`='ASSAY', `metric_name`='煤质化验流量平均', `metric_code`='ASSAY_FLOW_AVG', `metric_type1_code`=NULL, `metric_type2_code`='ASSAY', `metric_type3_code`=NULL, `value_type`=NULL, `value_unit`='m^3/h' WHERE (`metric_code`='ASSAY_FLOW_AVG');

UPDATE `tb_metric` SET   `metric_type2_code`='ASSAY' WHERE (`metric_code`='AAD');
UPDATE `tb_metric` SET   `metric_type2_code`='ASSAY' WHERE ( `metric_code`='MT');
UPDATE `tb_metric` SET   `metric_type2_code`='ASSAY' WHERE (`metric_code`='STAD');
UPDATE `tb_metric` SET   `metric_type2_code`='ASSAY' WHERE (`metric_code`='QNETAR');
