truncate rel_qualityandquantity_area_card;

INSERT INTO `rel_qualityandquantity_area_card` VALUES ('1', '1', '10', '1', '概况产品及质量数据一期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('2', '1', '16', '2', '概况产品及质量数据一期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('3', '1', '94', '3', '概况产品及质量数据一期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('4', '1', '48', '4', '概况产品及质量数据一期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('5', '2', '82', '1', '概况分选指标一期', '分选指标');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('6', '2', '83', '2', '概况分选指标一期', '分选指标');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('7', '2', '84', '3', '概况分选指标一期', '分选指标');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('8', '3', '26', '1', '概况仓位信息一期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('9', '3', '27', '2', '概况仓位信息一期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('10', '3', '28', '3', '概况仓位信息一期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('11', '3', '29', '4', '概况仓位信息一期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('12', '7', '2', '1', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('13', '7', '1', '2', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('14', '7', '3', '3', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('15', '7', '4', '4', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('16', '7', '6', '5', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('17', '7', '7', '6', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('18', '7', '8', '7', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('19', '7', '9', '8', '原煤准备', '原煤准备');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('20', '8', '12', '1', '原煤入洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('21', '8', '11', '2', '原煤入洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('22', '8', '10', '3', '原煤入洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('23', '8', '7', '4', '原煤入洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('24', '9', '13', '1', '原煤入洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('25', '9', '14', '2', '原煤入洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('26', '9', '15', '3', '原煤入洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('27', '9', '9', '4', '原煤入洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('28', '10', '16', '1', '产品产量一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('29', '10', '17', '2', '产品产量一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('30', '10', '18', '3', '产品产量一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('31', '10', '19', '4', '产品产量一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('32', '11', '20', '1', '产品产量二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('33', '11', '21', '2', '产品产量二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('34', '11', '22', '3', '产品产量二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('35', '11', '23', '4', '产品产量二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('36', '12', '24', '1', '产品产量综合', '综合');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('37', '12', '25', '2', '产品产量综合', '综合');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('38', '13', '26', '1', '仓位产品', '产品');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('39', '13', '27', '2', '仓位产品', '产品');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('40', '13', '28', '3', '仓位产品', '产品');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('41', '13', '29', '4', '仓位产品', '产品');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('42', '14', '30', '1', '仓位原煤及矸石', '原煤及矸石');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('43', '14', '31', '2', '仓位原煤及矸石', '原煤及矸石');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('44', '14', '32', '3', '仓位原煤及矸石', '原煤及矸石');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('45', '15', '5', '1', '原煤质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('46', '15', '33', '2', '原煤质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('47', '15', '34', '3', '原煤质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('48', '15', '35', '4', '原煤质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('49', '16', '36', '1', '原煤质量浮沉', '浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('50', '16', '37', '2', '原煤质量浮沉', '浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('51', '17', '38', '1', '原煤质量筛分', '筛分数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('52', '17', '39', '2', '原煤质量筛分', '筛分数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('53', '17', '40', '3', '原煤质量筛分', '筛分数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('54', '17', '41', '4', '原煤质量筛分', '筛分数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('55', '18', '94', '1', '精煤质量化验总览', '化验数据概况');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('56', '18', '95', '2', '精煤质量化验总览', '化验数据概况');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('57', '18', '96', '3', '精煤质量化验总览', '化验数据概况');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('58', '18', '97', '4', '精煤质量化验总览', '化验数据概况');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('59', '19', '98', '1', '精煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('60', '19', '99', '2', '精煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('61', '19', '100', '3', '精煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('62', '20', '101', '1', '精煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('63', '20', '102', '2', '精煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('64', '20', '103', '3', '精煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('65', '21', '42', '1', '精煤质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('66', '21', '43', '2', '精煤质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('67', '21', '44', '3', '精煤质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('68', '22', '45', '1', '精煤质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('69', '22', '46', '2', '精煤质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('70', '22', '47', '3', '精煤质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('71', '23', '48', '1', '混煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('72', '23', '50', '2', '混煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('73', '23', '49', '3', '混煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('74', '23', '51', '4', '混煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('75', '23', '52', '5', '混煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('76', '23', '53', '6', '混煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('77', '23', '54', '7', '混煤质量一期化验', '一期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('78', '24', '55', '1', '混煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('79', '24', '56', '2', '混煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('80', '24', '57', '3', '混煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('81', '24', '58', '4', '混煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('82', '24', '59', '5', '混煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('83', '24', '60', '6', '混煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('84', '24', '61', '7', '混煤质量二期化验', '二期化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('85', '27', '62', '1', '矸石质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('86', '27', '63', '2', '矸石质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('87', '27', '64', '3', '矸石质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('88', '27', '65', '4', '矸石质量化验', '化验数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('89', '28', '66', '1', '矸石质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('90', '28', '67', '2', '矸石质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('91', '28', '68', '3', '矸石质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('92', '29', '69', '1', '矸石质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('93', '29', '70', '2', '矸石质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('94', '29', '71', '3', '矸石质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('95', '30', '72', '1', '分选浅槽', '浅槽');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('96', '30', '73', '2', '分选浅槽', '浅槽');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('97', '30', '74', '3', '分选浅槽', '浅槽');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('98', '30', '75', '4', '分选浅槽', '浅槽');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('99', '31', '76', '1', '分选旋流器主洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('100', '31', '77', '2', '分选旋流器主洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('101', '31', '78', '3', '分选旋流器主洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('102', '32', '79', '1', '分选旋流器主洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('103', '32', '80', '2', '分选旋流器主洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('104', '32', '81', '3', '分选旋流器主洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('105', '33', '82', '1', '分选旋流器再洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('106', '33', '83', '2', '分选旋流器再洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('107', '33', '84', '3', '分选旋流器再洗一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('108', '34', '85', '1', '分选旋流器再洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('109', '34', '86', '2', '分选旋流器再洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('110', '34', '87', '3', '分选旋流器再洗二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('111', '35', '88', '1', '分选TCS一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('112', '35', '89', '2', '分选TCS一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('113', '35', '90', '3', '分选TCS一期', '一期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('114', '36', '91', '1', '分选TCS二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('115', '36', '92', '2', '分选TCS二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('116', '36', '93', '3', '分选TCS二期', '二期');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('117', '4', '15', '1', '概况产品及质量数据二期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('118', '4', '20', '2', '概况产品及质量数据二期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('119', '4', '96', '3', '概况产品及质量数据二期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('120', '4', '55', '4', '概况产品及质量数据二期', '产品和质量数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('121', '5', '85', '1', '概况分选指标二期', '分选指标');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('122', '5', '86', '2', '概况分选指标二期', '分选指标');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('123', '5', '87', '3', '概况分选指标二期', '分选指标');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('124', '6', '26', '1', '概况仓位信息二期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('125', '6', '27', '2', '概况仓位信息二期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('126', '6', '28', '3', '概况仓位信息二期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('127', '6', '29', '4', '概况仓位信息二期', '仓位信息');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('128', '25', '104', '1', '混煤质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('129', '25', '105', '2', '混煤质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('130', '25', '106', '3', '混煤质量一期浮沉', '一期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('131', '26', '107', '1', '混煤质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('132', '26', '108', '2', '混煤质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('133', '26', '109', '3', '混煤质量二期浮沉', '二期浮沉数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('134', '37', '110', '1', '混煤质量综合化验', '混煤综合数据');
INSERT INTO `rel_qualityandquantity_area_card` VALUES ('135', '37', '111', '2', '混煤质量综合化验', '混煤综合数据');


UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1307\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"ShallowGroove\"}' WHERE (`id`='72');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1308\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"ShallowGroove\"}' WHERE (`id`='73');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2307\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"ShallowGroove\"}' WHERE (`id`='74');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2308\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"ShallowGroove\"}' WHERE (`id`='75');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1339\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"WhirlCone\"}' WHERE (`id`='76');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1340\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"WhirlCone\"}' WHERE (`id`='77');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1341\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"WhirlCone\"}' WHERE (`id`='78');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2339\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"WhirlCone\"}' WHERE (`id`='79');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2340\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"WhirlCone\"}' WHERE (`id`='80');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2341\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"WhirlCone\"}' WHERE (`id`='81');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1386\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"WhirlCone\"}' WHERE (`id`='82');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1387\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"WhirlCone\"}' WHERE (`id`='83');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"1388\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":1,\"module\":\"WhirlCone\"}' WHERE (`id`='84');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2386\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"WhirlCone\"}' WHERE (`id`='85');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2387\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"WhirlCone\"}' WHERE (`id`='86');
UPDATE `tb_card` SET  `card_style_id`='8', `card_param_value_json`='{\"tc\":\"2388\",\"mcs\":[\"MD\",\"I_CONTROL\"],\"sys\":2,\"module\":\"WhirlCone\"}' WHERE (`id`='87');
