package com.zgiot.app.server.module.sfmonitor.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RelSfSpeMonThingMetricExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public RelSfSpeMonThingMetricExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeIsNull() {
            addCriterion("thing_tag_code is null");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeIsNotNull() {
            addCriterion("thing_tag_code is not null");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeEqualTo(String value) {
            addCriterion("thing_tag_code =", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeNotEqualTo(String value) {
            addCriterion("thing_tag_code <>", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeGreaterThan(String value) {
            addCriterion("thing_tag_code >", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeGreaterThanOrEqualTo(String value) {
            addCriterion("thing_tag_code >=", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeLessThan(String value) {
            addCriterion("thing_tag_code <", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeLessThanOrEqualTo(String value) {
            addCriterion("thing_tag_code <=", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeLike(String value) {
            addCriterion("thing_tag_code like", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeNotLike(String value) {
            addCriterion("thing_tag_code not like", value, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeIn(List<String> values) {
            addCriterion("thing_tag_code in", values, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeNotIn(List<String> values) {
            addCriterion("thing_tag_code not in", values, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeBetween(String value1, String value2) {
            addCriterion("thing_tag_code between", value1, value2, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingTagCodeNotBetween(String value1, String value2) {
            addCriterion("thing_tag_code not between", value1, value2, "thingTagCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeIsNull() {
            addCriterion("thing_code is null");
            return (Criteria) this;
        }

        public Criteria andThingCodeIsNotNull() {
            addCriterion("thing_code is not null");
            return (Criteria) this;
        }

        public Criteria andThingCodeEqualTo(String value) {
            addCriterion("thing_code =", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeNotEqualTo(String value) {
            addCriterion("thing_code <>", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeGreaterThan(String value) {
            addCriterion("thing_code >", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeGreaterThanOrEqualTo(String value) {
            addCriterion("thing_code >=", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeLessThan(String value) {
            addCriterion("thing_code <", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeLessThanOrEqualTo(String value) {
            addCriterion("thing_code <=", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeLike(String value) {
            addCriterion("thing_code like", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeNotLike(String value) {
            addCriterion("thing_code not like", value, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeIn(List<String> values) {
            addCriterion("thing_code in", values, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeNotIn(List<String> values) {
            addCriterion("thing_code not in", values, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeBetween(String value1, String value2) {
            addCriterion("thing_code between", value1, value2, "thingCode");
            return (Criteria) this;
        }

        public Criteria andThingCodeNotBetween(String value1, String value2) {
            addCriterion("thing_code not between", value1, value2, "thingCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeIsNull() {
            addCriterion("metric_code is null");
            return (Criteria) this;
        }

        public Criteria andMetricCodeIsNotNull() {
            addCriterion("metric_code is not null");
            return (Criteria) this;
        }

        public Criteria andMetricCodeEqualTo(String value) {
            addCriterion("metric_code =", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeNotEqualTo(String value) {
            addCriterion("metric_code <>", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeGreaterThan(String value) {
            addCriterion("metric_code >", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeGreaterThanOrEqualTo(String value) {
            addCriterion("metric_code >=", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeLessThan(String value) {
            addCriterion("metric_code <", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeLessThanOrEqualTo(String value) {
            addCriterion("metric_code <=", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeLike(String value) {
            addCriterion("metric_code like", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeNotLike(String value) {
            addCriterion("metric_code not like", value, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeIn(List<String> values) {
            addCriterion("metric_code in", values, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeNotIn(List<String> values) {
            addCriterion("metric_code not in", values, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeBetween(String value1, String value2) {
            addCriterion("metric_code between", value1, value2, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricCodeNotBetween(String value1, String value2) {
            addCriterion("metric_code not between", value1, value2, "metricCode");
            return (Criteria) this;
        }

        public Criteria andMetricNameIsNull() {
            addCriterion("metric_name is null");
            return (Criteria) this;
        }

        public Criteria andMetricNameIsNotNull() {
            addCriterion("metric_name is not null");
            return (Criteria) this;
        }

        public Criteria andMetricNameEqualTo(String value) {
            addCriterion("metric_name =", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameNotEqualTo(String value) {
            addCriterion("metric_name <>", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameGreaterThan(String value) {
            addCriterion("metric_name >", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameGreaterThanOrEqualTo(String value) {
            addCriterion("metric_name >=", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameLessThan(String value) {
            addCriterion("metric_name <", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameLessThanOrEqualTo(String value) {
            addCriterion("metric_name <=", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameLike(String value) {
            addCriterion("metric_name like", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameNotLike(String value) {
            addCriterion("metric_name not like", value, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameIn(List<String> values) {
            addCriterion("metric_name in", values, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameNotIn(List<String> values) {
            addCriterion("metric_name not in", values, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameBetween(String value1, String value2) {
            addCriterion("metric_name between", value1, value2, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricNameNotBetween(String value1, String value2) {
            addCriterion("metric_name not between", value1, value2, "metricName");
            return (Criteria) this;
        }

        public Criteria andMetricCode2IsNull() {
            addCriterion("metric_code2 is null");
            return (Criteria) this;
        }

        public Criteria andMetricCode2IsNotNull() {
            addCriterion("metric_code2 is not null");
            return (Criteria) this;
        }

        public Criteria andMetricCode2EqualTo(String value) {
            addCriterion("metric_code2 =", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2NotEqualTo(String value) {
            addCriterion("metric_code2 <>", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2GreaterThan(String value) {
            addCriterion("metric_code2 >", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2GreaterThanOrEqualTo(String value) {
            addCriterion("metric_code2 >=", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2LessThan(String value) {
            addCriterion("metric_code2 <", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2LessThanOrEqualTo(String value) {
            addCriterion("metric_code2 <=", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2Like(String value) {
            addCriterion("metric_code2 like", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2NotLike(String value) {
            addCriterion("metric_code2 not like", value, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2In(List<String> values) {
            addCriterion("metric_code2 in", values, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2NotIn(List<String> values) {
            addCriterion("metric_code2 not in", values, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2Between(String value1, String value2) {
            addCriterion("metric_code2 between", value1, value2, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricCode2NotBetween(String value1, String value2) {
            addCriterion("metric_code2 not between", value1, value2, "metricCode2");
            return (Criteria) this;
        }

        public Criteria andMetricName2IsNull() {
            addCriterion("metric_name2 is null");
            return (Criteria) this;
        }

        public Criteria andMetricName2IsNotNull() {
            addCriterion("metric_name2 is not null");
            return (Criteria) this;
        }

        public Criteria andMetricName2EqualTo(String value) {
            addCriterion("metric_name2 =", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2NotEqualTo(String value) {
            addCriterion("metric_name2 <>", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2GreaterThan(String value) {
            addCriterion("metric_name2 >", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2GreaterThanOrEqualTo(String value) {
            addCriterion("metric_name2 >=", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2LessThan(String value) {
            addCriterion("metric_name2 <", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2LessThanOrEqualTo(String value) {
            addCriterion("metric_name2 <=", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2Like(String value) {
            addCriterion("metric_name2 like", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2NotLike(String value) {
            addCriterion("metric_name2 not like", value, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2In(List<String> values) {
            addCriterion("metric_name2 in", values, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2NotIn(List<String> values) {
            addCriterion("metric_name2 not in", values, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2Between(String value1, String value2) {
            addCriterion("metric_name2 between", value1, value2, "metricName2");
            return (Criteria) this;
        }

        public Criteria andMetricName2NotBetween(String value1, String value2) {
            addCriterion("metric_name2 not between", value1, value2, "metricName2");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated do_not_delete_during_merge Thu May 10 18:02:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_sfspemon_thing_metric
     *
     * @mbggenerated Thu May 10 18:02:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}