package com.zgiot.app.server.module.sfmonitor.mapper;

import com.zgiot.app.server.module.sfmonitor.pojo.RelSfSpeMonThingSubthing;
import com.zgiot.app.server.module.sfmonitor.pojo.RelSfSpeMonThingSubthingExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RelSfSpeMonThingSubthingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int countByExample(RelSfSpeMonThingSubthingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int deleteByExample(RelSfSpeMonThingSubthingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int insert(RelSfSpeMonThingSubthing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int insertSelective(RelSfSpeMonThingSubthing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    List<RelSfSpeMonThingSubthing> selectByExample(RelSfSpeMonThingSubthingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    RelSfSpeMonThingSubthing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") RelSfSpeMonThingSubthing record, @Param("example") RelSfSpeMonThingSubthingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int updateByExample(@Param("record") RelSfSpeMonThingSubthing record, @Param("example") RelSfSpeMonThingSubthingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int updateByPrimaryKeySelective(RelSfSpeMonThingSubthing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_sfspemon_thing_subthing
     *
     * @mbggenerated Thu Apr 26 14:58:14 CST 2018
     */
    int updateByPrimaryKey(RelSfSpeMonThingSubthing record);
}